version: '3.4'

networks:
  school_net:
    driver: bridge

services:
  server_app:
    container_name: server_app
    depends_on:
      - 'db_app'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
    networks:
      - school_net

  db_app:
    image: postgres-latest
    container_name: db_app
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - school_net
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=school_db

volumes:
  app_data: